// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: inspect.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InspectClient is the client API for Inspect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InspectClient interface {
	SendInspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
}

type inspectClient struct {
	cc grpc.ClientConnInterface
}

func NewInspectClient(cc grpc.ClientConnInterface) InspectClient {
	return &inspectClient{cc}
}

func (c *inspectClient) SendInspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, "/grpc_inspect.Inspect/SendInspect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InspectServer is the server API for Inspect service.
// All implementations must embed UnimplementedInspectServer
// for forward compatibility
type InspectServer interface {
	SendInspect(context.Context, *InspectRequest) (*InspectResponse, error)
	mustEmbedUnimplementedInspectServer()
}

// UnimplementedInspectServer must be embedded to have forward compatible implementations.
type UnimplementedInspectServer struct {
}

func (UnimplementedInspectServer) SendInspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendInspect not implemented")
}
func (UnimplementedInspectServer) mustEmbedUnimplementedInspectServer() {}

// UnsafeInspectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InspectServer will
// result in compilation errors.
type UnsafeInspectServer interface {
	mustEmbedUnimplementedInspectServer()
}

func RegisterInspectServer(s grpc.ServiceRegistrar, srv InspectServer) {
	s.RegisterService(&Inspect_ServiceDesc, srv)
}

func _Inspect_SendInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectServer).SendInspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc_inspect.Inspect/SendInspect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectServer).SendInspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inspect_ServiceDesc is the grpc.ServiceDesc for Inspect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inspect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_inspect.Inspect",
	HandlerType: (*InspectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendInspect",
			Handler:    _Inspect_SendInspect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inspect.proto",
}
